### ISSUE TITLE
stm32f407 discovery serial example does not work

### ISSUE THREAD

**Issue by niclashoyer** [stm32-rs/synopsys-usb-otg#18]
Hi,

I tried to run the serial example on my stm32f407 discovery board: https://github.com/Disasm/usb-otg-workspace/blob/master/example-f407-board/examples/serial.rs

The code runs fine so far, the device enumerates:

```bash
$ lsusb
Bus 004 Device 008: ID 0483:3748 STMicroelectronics ST-LINK/V2
Bus 002 Device 012: ID 16c0:27dd Van Ooijen Technische Informatica CDC-ACM class devices (modems)
…
```

But it does not send/receive any characters on `/dev/ttyACM0`. I already tried to investigate it, as there is no error so far. The only thing that I see is that it never actually receives data. I already tried several clients (screen, tio, minicom), to no avail. I also uninstalled ModemManager, just in case.

Using `usbmon` and wireshark I see that the device connects successfully, but then just stops communicating after the `SET LINE CODING Request`:

![Bildschirmfoto von 2021-04-12 16-10-28](https://user-images.githubusercontent.com/175808/114408381-a3834700-9ba9-11eb-842e-52aa89d479c2.png)

Full wireshark dump: [usb.pcapng.gz](https://github.com/stm32-rs/synopsys-usb-otg/files/6297342/usb.pcapng.gz)

Is there any way I could debug this further?

**Comment by niclashoyer** [comment]
Just tested on a different computer and it worked there, strange. `dmesg` output was also a bit different. I'll try to dump usb messages there and compare them.

**Comment by Disasm** [comment]
A silly question: a you running a release build of a firmware?

**Comment by niclashoyer** [comment]
yes, the firmware was identical (actually flashed it on the non-working computer and just plugged it into the other computer)

**Comment by niclashoyer** [comment]
Ok, here is the dump of the communication from the working computer:

[usb.pcapng.gz](https://github.com/stm32-rs/synopsys-usb-otg/files/6298373/usb.pcapng.gz)

As far as I can see the communication is the same until `URB_CONTROL out` and then it just starts communicating (I just pressed `abc`):

![Bildschirmfoto von 2021-04-12 18-37-36](https://user-images.githubusercontent.com/175808/114430159-71c8ab00-9bbe-11eb-81cf-13a3000e9510.png)

I already tested on another computer and it also worked there, so I think it must be something with the OS, but I don't know how to proceed from here.

I think this can be closed for now.
